### ISSUE TITLE
Crash - Exception in server tick loop

### ISSUE THREAD

**Issue by Luke616** [jabelar/MovingLightSource-1.12#14] opened 2018-10-28 19:56 UTC
Having a crash which seems to be related to your mod:
https://paste.dimdev.org/pofafocuke.mccrash

I'm using MC ver1.12.2, Forge v.14.23.5.2772, and Moving Light Source v.10.13

When this occurred, I was holding a torch walking through a dark cave underground testing out the mod.

Thanks!

**Comment by dancc7t** [comment] 2018-10-28 22:31
same thing happened to me just right now, but i am using forge 14.23.5.2770

**Comment by jabelar** [comment] 2018-10-29 01:16
This is duplicate of issue #13 and should be fixed in version 1.0.14 posted on CurseForge.

**Closed as completed by jabelar** 2018-10-29 01:16 UTC
